apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: {{ .Values.name }}-{{ .Values.environment }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Release.Name }}-postgres