name: cadriciel-ci

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
        with:
          path: './'
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64
          tags: |
            cerema/machinasapiens:${{ steps.package-version.outputs.version }}
            cerema/machinasapiens:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
#      - name: Deploy
#        uses: WyriHaximus/github-action-helm3@v2.0
#        with:
#          exec: helm upgrade --install console ./kubernetes --values=./kubernetes/values.yaml --create-namespace --namespace xxx
#          kubeconfig: '${{ secrets.KUBECONFIG }}'
